services:
    application:
        image: ghcr.io/mops1k/php-cli-dev-docker:latest
        working_dir: /app
        environment:
            XDEBUG_MODE: "debug,coverage,develop"
            XDEBUG_CONFIG: "client_host=host.docker.internal"
            PHP_IDE_CONFIG: "serverName=application"
        command: tail -f >/dev/null
        volumes:
            -   ./:/app/:rw
